server:
  port: 8202

spring:
  # 关闭多数据源自动装配
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: febs
        password: 123456
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1

info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
# 1,到认证服务器里校验当前请求头中的令牌是否为合法的令牌；2,通过当前令牌获取对应的用户信息
security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8301/auth/user

feign:
  hystrix:
    enabled: true

hystrix:
  shareSecurityContext: true


