server:
  port: 8301
spring:
  application:
    name: FEBS-Gateway
  boot:
    admin:
      client:
#        url: http://${febs-monitor-admin}:8401
        url: http://localhost:8401
        username: febs
        password: 123456
  cloud:
    gateway:
      routes:
        - id: FEBS-Auth
          uri: lb://FEBS-Auth
          predicates:
            - Path=/auth/**
          filters:
            - name: Hystrix
              args:
                name: authfallback
                fallbackUri: forward:/fallback/FEBS-Auth
        - id: FEBS-Server-System
          uri: lb://FEBS-Server-System
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                # HystrixCommandKey
                name: systemfallback
                fallbackUri: forward:/fallback/FEBS-Server-System
        - id: FEBS-Server-test
          uri: lb://FEBS-Server-Test
          predicates:
            - Path=/test/**
          filters:
            - name: Hystrix
              args:
                name: testfallback
                fallbackUri: forward:/fallback/FEBS-Server-Test
      default-filters:
        - StripPrefix=1

#如果要针对不同的路由设置不同的超时时间，可以按照下面格式配置
#  command:
#    HystrixCommandKey:
#      execution:
#        isolation:
#          thread:
#            timeoutinMilliseconds:
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
#    serviceUrl:
#      defaultZone: http://febs:123456@${febs-register}:8001/register/eureka/
    serviceUrl:
      defaultZone: http://febs:123456@localhost:8001/register/eureka/

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: health,info,gateway